language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit NeoPixel"

script:
   - build_main_platforms
