language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
#     - PRETTYNAME="Adafruit FT6206 Arduino Library"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   # - arduino --install-library "Adafruit ILI9341","Adafruit GFX Library"

script:
   - build_main_platforms
