name: Arduino Sketch CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install extra libraries
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/cyborg5/IRLib2.git /home/runner/Arduino/libraries/IRLib2

    - name: test platforms
      run: python3 ci/build_platform.py metro_m0

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 
