name: Arduino Sketch CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: brentru/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install IRLib2 correctly
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/cyborg5/IRLib2.git
        mv IRLib2/IRLib2 /home/runner/Arduino/libraries/IRLib2
        mv IRLib2/IRLibFreq /home/runner/Arduino/libraries/IRLibFreq
        mv IRLib2/IRLibProtocols /home/runner/Arduino/libraries/IRLibProtocols
        mv IRLib2/IRLibRecv /home/runner/Arduino/libraries/IRLibRecv
        mv IRLib2/IRLibRecvPCI /home/runner/Arduino/libraries/IRLibRecvPCI

    - name: test platforms
      run: python3 ci/build_platform.py uno

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 
